# Python CircleCI 2.0 configuration file with sonar cloud support
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # Step 3: pytest
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest
      # Step 4: behave test
      - run:
          name: behave test
          command: |
            . venv/bin/activate
            behave test/features
      # Step 5: Sonar cloud report
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud